# Generated by Django 2.0.13 on 2020-05-15 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dataimage',
            name='image',
        ),
        migrations.AddField(
            model_name='dataimage',
            name='path',
            field=models.ImageField(blank=True, upload_to='img/'),
        ),
    ]
